name: Build without Dockerimage

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.51
    steps:
      - name: Install requirements
        run: |
          apt-get update -y
          apt-get install -y pkg-config build-essential ninja-build brotli autoconf autoconf-archive automake jq
          apt-get install -y zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build emception
        run: ./build.sh
      - name: Bundle emception
        working-directory: bundling
        run: |
          npm install
          npm run bundle
      - name: Archive artifacts
        working-directory: bundling
        run: zip -r ../emception.zip dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: emception-bundle
          path: emception.zip
